//clk, rst are not generated by the real silicon i.e; memory or processor. So, it has to be generated by external souurce. so we generate here in tb.
module tb;

parameter DEPTH = 1024;
parameter ADDR_WIDTH = $clog2(DEPTH);
parameter WIDTH = 8;

//All the inputs to tb are reg type and remaining everything are wires 
wire [ADDR_WIDTH-1:0] n1; //Names for wires can be anything as you wish. We just have to make sure, we connected everything correctly.
wire [WIDTH-1:0] n2;
wire [WIDTH-1:0] n3;
wire n4;
wire n5;
wire n6;

reg clk, rst; //TB is generating the clk and giving it as an input.

//Instantiations of the modules 
processor inst1(.clk_i(clk),
				.rst_i(rst),
				.addr_o(n1),
				.wr_data_o(n2),
				.rd_data_i(n3),
				.wr_rd_o(n4),
				.valid_o(n5),
				.ready_i(n6));

memory inst2(.clk_i(clk),
			 .rst_i(rst),
			 .addr_i(n1),
			 .wr_data_i(n2),
			 .rd_data_o(n3),
			 .wr_rd_i(n4),
			 .valid_i(n5),
			 .ready_o(n6));

endmodule 